spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/redis_cache_example
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true

